/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'
import { Route as QuizTopicIdTestIdRouteImport } from './routes/quiz.$topicId.$testId'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTopicIdTestIdRoute = QuizTopicIdTestIdRouteImport.update({
  id: '/quiz/$topicId/$testId',
  path: '/quiz/$topicId/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/quiz/$topicId/$testId': typeof QuizTopicIdTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/quiz/$topicId/$testId': typeof QuizTopicIdTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/quiz/$topicId/$testId': typeof QuizTopicIdTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/results' | '/topic/$topicId' | '/quiz/$topicId/$testId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/results' | '/topic/$topicId' | '/quiz/$topicId/$testId'
  id:
    | '__root__'
    | '/'
    | '/results'
    | '/topic/$topicId'
    | '/quiz/$topicId/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultsRoute: typeof ResultsRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
  QuizTopicIdTestIdRoute: typeof QuizTopicIdTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$topicId/$testId': {
      id: '/quiz/$topicId/$testId'
      path: '/quiz/$topicId/$testId'
      fullPath: '/quiz/$topicId/$testId'
      preLoaderRoute: typeof QuizTopicIdTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultsRoute: ResultsRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
  QuizTopicIdTestIdRoute: QuizTopicIdTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
